spring:
  datasource:
    druid:
      url: jdbc:mysql://localhost:3306/test?useSSL=false&characterEncoding=UTF-8&serverTimezone=UTC
      username: root
      password: 123456
      min-idle: 3  # 最小
      max-active: 10  # 最大
      initial-size: 3  # 初始化大小
      max-wait: 60000  # 连接超时时间
      time-between-eviction-runs-millis: 60000  # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
      min-evictable-idle-time-millis: 300000  # 指定一个空闲连接最少空闲多久后可被清除，单位是毫秒
      validationQuery: select 1
      test-while-idle: true  # 当连接空闲时是否执行连接测试
      test-on-borrow: false  # 当从连接池借用连接时是否测试该连接
      test-on-return: false  # 在连接归还到连接池时是否测试该连接
      filters: config,wall,stat  # 配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
      stat-view-servlet:
        enabled: true
        url-pattern: /druid/*
        reset-enable: true
  redis:
    lettuce:      pool:        max-active: 8
        max-idle: 8
        max-wait: -1ms
        min-idle: 3    password: 123456
    sentinel:      master: mymaster
      nodes:      - 192.168.104.29:26379
      - 192.168.104.29:26380
      - 192.168.104.29:26381

mybatis:  mapper-locations:  - classpath:mapper/*.xml
  type-aliases-package: org.eleven.model

mapper:  mappers:  - org.eleven.util.MyMapper
  identity: mysql

pagehelper:
  helper-dialect: mysql