
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/test?useSSL=false
    username: root
    password: 123456
    min-idle: 3  # 最小
    max-active: 10  # 最大
    initial-size: 3  # 初始化大小
    max-wait: 60000  # 连接超时时间
  redis:
    password:
    host: localhost
    lettuce:
      pool:
        max-active: 8
        max-idle: 8
        max-wait: -1ms
        min-idle: 3
  # 404抛异常
  mvc:
    throw-exception-if-no-handler-found: true
  resources:
    add-mappings: false

mybatis-plus:
  mapper-locations:
    - classpath:mapper/*.xml
  global-config:
    banner: false
    db-config:
      logic-delete-field: deleted
      logic-delete-value: 1
      logic-not-delete-value: 0

pagehelper:
  helper-dialect: mysql
logging:
  level:
    org.eleven.mapper: debug